# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\26158\Desktop\PAP\segunda_tela.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(544, 671)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 140, 221, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.lineEdit_reparada = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_reparada.setGeometry(QtCore.QRect(30, 190, 221, 38))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setItalic(False)
        self.lineEdit_reparada.setFont(font)
        self.lineEdit_reparada.setStyleSheet("border-radius:15px;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"background-color:rgb(170,255,255)\n"
"")
        self.lineEdit_reparada.setText("")
        self.lineEdit_reparada.setObjectName("lineEdit_reparada")
        self.lineEdit_atribuido = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_atribuido.setGeometry(QtCore.QRect(30, 280, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setItalic(True)
        self.lineEdit_atribuido.setFont(font)
        self.lineEdit_atribuido.setStyleSheet("border-radius:15px;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"background-color:rgb(170,255,255)")
        self.lineEdit_atribuido.setText("")
        self.lineEdit_atribuido.setObjectName("lineEdit_atribuido")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 240, 149, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(390, 580, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButton.setStyleSheet(" border-radius: 20px;\n"
"  border-style: outset;\n"
"  border-width: 2px;\n"
"  background-color: rgb(79, 255, 129);\n"
"color: rgb(255, 255, 255);")
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_voltar = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_voltar.setGeometry(QtCore.QRect(210, 580, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_voltar.setFont(font)
        self.pushButton_voltar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_voltar.setStyleSheet(" border-radius: 20px;\n"
"  border-style: outset;\n"
"  border-width: 2px;\n"
"background-color: rgb(255, 0, 0);")
        self.pushButton_voltar.setObjectName("pushButton_voltar")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 580, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet(" border-radius: 20px;\n"
"background-color: rgb(137, 253, 186);\n"
"  border-style: outset;\n"
"  border-width: 2px;\n"
"color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 330, 261, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 370, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setItalic(False)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border-radius:15px;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"background-color:rgb(170,255,255)\n"
"")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.dateEdit = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit.setGeometry(QtCore.QRect(30, 180, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.dateEdit.setFont(font)
        self.dateEdit.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.dateEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dateEdit.setStyleSheet("border-radius:15px;\n"
"border-style:outset;\n"
"border-width:2px;\n"
"background-color:rgb(170,255,255);\n"
"color: rgb(0, 0, 0);")
        self.dateEdit.setFrame(True)
        self.dateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 7, 9), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.pushButton_voltar_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_voltar_2.setGeometry(QtCore.QRect(210, 580, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_voltar_2.setFont(font)
        self.pushButton_voltar_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_voltar_2.setStyleSheet(" border-radius: 20px;\n"
"  border-style: outset;\n"
"  border-width: 2px;\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.pushButton_voltar_2.setObjectName("pushButton_voltar_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 541, 671))
        self.label_2.setStyleSheet(" border-radius: 20px;\n"
"border-image: url(:/segundatela/logo.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, -50, 541, 671))
        self.label_5.setStyleSheet(" border-radius: 20px;\n"
"border-image: url(:/segundatela/logo.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_2.raise_()
        self.label.raise_()
        self.lineEdit_reparada.raise_()
        self.lineEdit_atribuido.raise_()
        self.label_3.raise_()
        self.pushButton.raise_()
        self.pushButton_voltar.raise_()
        self.pushButton_3.raise_()
        self.label_4.raise_()
        self.lineEdit_2.raise_()
        self.dateEdit.raise_()
        self.pushButton_voltar_2.raise_()
        self.label_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.lineEdit_reparada, self.lineEdit_atribuido)
        MainWindow.setTabOrder(self.lineEdit_atribuido, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_voltar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Data Planeada:"))
        self.label_3.setText(_translate("MainWindow", "Atribuido a:"))
        self.pushButton.setText(_translate("MainWindow", "Salvar"))
        self.pushButton_voltar.setText(_translate("MainWindow", "Voltar"))
        self.pushButton_3.setText(_translate("MainWindow", "Desatribuir"))
        self.label_4.setText(_translate("MainWindow", "Status do Serviço:"))
        self.dateEdit.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.pushButton_voltar_2.setText(_translate("MainWindow", "cancelar"))
import segundatela_rc
